### ISSUE TITLE
Stupid test.

### ISSUE THREAD

**Issue by VinceSanityyy** [VinceSanityyy/GuidanceExam-Scheduler#11]
![image](https://user-images.githubusercontent.com/38340124/77661070-1d538d00-6fb5-11ea-8298-a45f4cdc321a.png)

**Comment by VinceSanityyy** [comment]
Need to add this to `.yaml` file in order to test php specific versions and other OS

```
runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl #optional
        ini-values: "post_max_size=256M" #optional
    - name: Check PHP Version
      run: php
```
